/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PreferenceService } from "../preference.service";
import { PreferenceCreateInput } from "./PreferenceCreateInput";
import { Preference } from "./Preference";
import { PreferenceFindManyArgs } from "./PreferenceFindManyArgs";
import { PreferenceWhereUniqueInput } from "./PreferenceWhereUniqueInput";
import { PreferenceUpdateInput } from "./PreferenceUpdateInput";

export class PreferenceControllerBase {
  constructor(protected readonly service: PreferenceService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Preference })
  async createPreference(
    @common.Body() data: PreferenceCreateInput
  ): Promise<Preference> {
    return await this.service.createPreference({
      data: data,
      select: {
        context: true,
        createdAt: true,
        id: true,
        updatedAt: true,
        userId: true,
        value: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Preference] })
  @ApiNestedQuery(PreferenceFindManyArgs)
  async preferences(@common.Req() request: Request): Promise<Preference[]> {
    const args = plainToClass(PreferenceFindManyArgs, request.query);
    return this.service.preferences({
      ...args,
      select: {
        context: true,
        createdAt: true,
        id: true,
        updatedAt: true,
        userId: true,
        value: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Preference })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async preference(
    @common.Param() params: PreferenceWhereUniqueInput
  ): Promise<Preference | null> {
    const result = await this.service.preference({
      where: params,
      select: {
        context: true,
        createdAt: true,
        id: true,
        updatedAt: true,
        userId: true,
        value: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Preference })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updatePreference(
    @common.Param() params: PreferenceWhereUniqueInput,
    @common.Body() data: PreferenceUpdateInput
  ): Promise<Preference | null> {
    try {
      return await this.service.updatePreference({
        where: params,
        data: data,
        select: {
          context: true,
          createdAt: true,
          id: true,
          updatedAt: true,
          userId: true,
          value: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Preference })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deletePreference(
    @common.Param() params: PreferenceWhereUniqueInput
  ): Promise<Preference | null> {
    try {
      return await this.service.deletePreference({
        where: params,
        select: {
          context: true,
          createdAt: true,
          id: true,
          updatedAt: true,
          userId: true,
          value: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
